CREATE TABLE IF NOT EXISTS `admin_upload_jobs` (
  `id` varchar(191) NOT NULL,
  `kind` enum('exam_config','exam_package','student_class') NOT NULL,
  `file_name` varchar(191) NOT NULL,
  `status` varchar(191) NOT NULL DEFAULT 'received',
  `notes` text DEFAULT NULL,
  `uploaded_by` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`id`),
  KEY `admin_upload_jobs_uploaded_by_fkey` (`uploaded_by`),
  CONSTRAINT `admin_upload_jobs_uploaded_by_fkey` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `answer_drafts` (
  `id` varchar(191) NOT NULL,
  `session_id` varchar(191) NOT NULL,
  `question_id` varchar(191) NOT NULL,
  `value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`value`)),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `answer_drafts_session_id_question_id_key` (`session_id`,`question_id`),
  KEY `answer_drafts_session_id_idx` (`session_id`),
  KEY `answer_drafts_question_id_fkey` (`question_id`),
  CONSTRAINT `answer_drafts_question_id_fkey` FOREIGN KEY (`question_id`) REFERENCES `exam_questions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `answer_drafts_session_id_fkey` FOREIGN KEY (`session_id`) REFERENCES `exam_sessions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `app_config_ai` (
  `id` varchar(191) NOT NULL DEFAULT 'ai',
  `text_provider` varchar(191) NOT NULL DEFAULT 'claude',
  `text_model` varchar(191) NOT NULL DEFAULT 'claude-haiku-4-5',
  `temperature` double NOT NULL DEFAULT 0.4,
  `image_provider` varchar(191) NOT NULL DEFAULT 'gemini',
  `updated_by` varchar(191) DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL,
  `ai_keys` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`ai_keys`)),
  PRIMARY KEY (`id`),
  KEY `app_config_ai_updated_by_fkey` (`updated_by`),
  CONSTRAINT `app_config_ai_updated_by_fkey` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `bank_questions` (
  `id` varchar(191) NOT NULL,
  `type` enum('single_choice','multi_select','short_text','numeric','essay') NOT NULL,
  `language` varchar(191) DEFAULT NULL,
  `subject` varchar(191) DEFAULT NULL,
  `topic` varchar(191) NOT NULL,
  `subtopic` varchar(191) DEFAULT NULL,
  `difficulty` enum('easy','medium','hard','hots','olympiad') DEFAULT NULL,
  `tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tags`)),
  `prompt` text NOT NULL,
  `options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`options`)),
  `points` double NOT NULL DEFAULT 1,
  `correct_answer` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`correct_answer`)),
  `explanation_text` text DEFAULT NULL,
  `created_by` varchar(191) DEFAULT NULL,
  `created_by_name` varchar(191) DEFAULT NULL,
  `source_file_name` varchar(191) DEFAULT NULL,
  `media_url` text DEFAULT NULL,
  `media_type` enum('image','audio','video') DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `uploaded_by` varchar(191) DEFAULT NULL,
  `uploaded_by_name` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `bank_questions_created_by_idx` (`created_by`),
  KEY `bank_questions_subject_idx` (`subject`),
  KEY `bank_questions_uploaded_by_idx` (`uploaded_by`),
  CONSTRAINT `bank_questions_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `bank_questions_uploaded_by_fkey` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `class_students` (
  `id` varchar(191) NOT NULL,
  `class_id` varchar(191) NOT NULL,
  `student_identifier` varchar(191) NOT NULL,
  `student_name` varchar(191) NOT NULL,
  `student_email` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `class_students_class_id_student_identifier_key` (`class_id`,`student_identifier`),
  KEY `class_students_class_id_idx` (`class_id`),
  CONSTRAINT `class_students_class_id_fkey` FOREIGN KEY (`class_id`) REFERENCES `student_classes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exam_access_tokens` (
  `id` varchar(191) NOT NULL,
  `exam_id` varchar(191) NOT NULL,
  `class_id` varchar(191) DEFAULT NULL,
  `token_digest` varchar(191) NOT NULL,
  `token_preview` varchar(191) NOT NULL,
  `max_uses` int(11) NOT NULL DEFAULT 1,
  `used_count` int(11) NOT NULL DEFAULT 0,
  `expires_at` datetime(3) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` varchar(191) DEFAULT NULL,
  `created_by_name` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `exam_access_tokens_token_digest_key` (`token_digest`),
  KEY `exam_access_tokens_exam_id_idx` (`exam_id`),
  KEY `exam_access_tokens_class_id_fkey` (`class_id`),
  KEY `exam_access_tokens_created_by_fkey` (`created_by`),
  CONSTRAINT `exam_access_tokens_class_id_fkey` FOREIGN KEY (`class_id`) REFERENCES `student_classes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `exam_access_tokens_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `exam_access_tokens_exam_id_fkey` FOREIGN KEY (`exam_id`) REFERENCES `exams` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exam_generation_prompts` (
  `id` varchar(191) NOT NULL,
  `upload_job_id` varchar(191) DEFAULT NULL,
  `config_order` int(11) NOT NULL DEFAULT 0,
  `exam_id` varchar(191) NOT NULL,
  `exam_title` varchar(191) NOT NULL,
  `config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`config`)),
  `prompt_text` text NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`id`),
  KEY `exam_generation_prompts_upload_job_id_idx` (`upload_job_id`),
  KEY `exam_generation_prompts_exam_id_idx` (`exam_id`),
  CONSTRAINT `exam_generation_prompts_upload_job_id_fkey` FOREIGN KEY (`upload_job_id`) REFERENCES `admin_upload_jobs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exam_media` (
  `id` varchar(191) NOT NULL,
  `question_id` varchar(191) NOT NULL,
  `type` enum('image','audio','video') NOT NULL,
  `url` text NOT NULL,
  `alt_text` varchar(191) DEFAULT NULL,
  `caption` varchar(191) DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`id`),
  KEY `exam_media_question_id_idx` (`question_id`),
  CONSTRAINT `exam_media_question_id_fkey` FOREIGN KEY (`question_id`) REFERENCES `exam_questions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exam_questions` (
  `id` varchar(191) NOT NULL,
  `exam_id` varchar(191) NOT NULL,
  `position` int(11) NOT NULL,
  `type` enum('single_choice','multi_select','short_text','numeric','essay') NOT NULL,
  `topic` varchar(191) NOT NULL,
  `tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tags`)),
  `prompt` text NOT NULL,
  `options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`options`)),
  `points` double NOT NULL DEFAULT 1,
  `source_bank_question_id` varchar(191) DEFAULT NULL,
  `correct_answer` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`correct_answer`)),
  `explanation_text` text DEFAULT NULL,
  `explanation_media` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`explanation_media`)),
  `language` varchar(191) DEFAULT NULL,
  `difficulty` enum('easy','medium','hard','hots','olympiad') DEFAULT NULL,
  `media_file` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `exam_questions_exam_id_position_key` (`exam_id`,`position`),
  KEY `exam_questions_exam_id_idx` (`exam_id`),
  CONSTRAINT `exam_questions_exam_id_fkey` FOREIGN KEY (`exam_id`) REFERENCES `exams` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exam_sessions` (
  `id` varchar(191) NOT NULL,
  `user_id` varchar(191) NOT NULL,
  `exam_id` varchar(191) NOT NULL,
  `attempt` int(11) NOT NULL DEFAULT 1,
  `status` enum('draft','submitted','expired') NOT NULL DEFAULT 'draft',
  `started_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `last_saved_at` datetime(3) DEFAULT NULL,
  `submitted_at` datetime(3) DEFAULT NULL,
  `token_id` varchar(191) DEFAULT NULL,
  `time_used_seconds` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `anti_cheat_events` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`anti_cheat_events`)),
  PRIMARY KEY (`id`),
  UNIQUE KEY `exam_sessions_user_id_exam_id_attempt_key` (`user_id`,`exam_id`,`attempt`),
  KEY `exam_sessions_user_id_exam_id_idx` (`user_id`,`exam_id`),
  KEY `exam_sessions_exam_id_fkey` (`exam_id`),
  KEY `exam_sessions_token_id_fkey` (`token_id`),
  CONSTRAINT `exam_sessions_exam_id_fkey` FOREIGN KEY (`exam_id`) REFERENCES `exams` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `exam_sessions_token_id_fkey` FOREIGN KEY (`token_id`) REFERENCES `exam_access_tokens` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `exam_sessions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exam_submissions` (
  `id` varchar(191) NOT NULL,
  `exam_id` varchar(191) NOT NULL,
  `user_id` varchar(191) NOT NULL,
  `session_id` varchar(191) DEFAULT NULL,
  `username` varchar(191) NOT NULL,
  `full_name` varchar(191) NOT NULL,
  `exam_name` varchar(191) NOT NULL,
  `exam_mode` enum('strict','try_out') NOT NULL,
  `attempt` int(11) NOT NULL DEFAULT 1,
  `passing_grade` int(11) NOT NULL,
  `final_score` double NOT NULL,
  `possible_score` double NOT NULL,
  `percent_score` double NOT NULL,
  `passed` tinyint(1) NOT NULL,
  `pending_essay_count` int(11) NOT NULL DEFAULT 0,
  `topic_breakdown` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`topic_breakdown`)),
  `answers_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`answers_snapshot`)),
  `manual_scores` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`manual_scores`)),
  `anti_cheat_events` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`anti_cheat_events`)),
  `review_items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`review_items`)),
  `submitted_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `graded_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `exam_submissions_user_id_exam_id_attempt_key` (`user_id`,`exam_id`,`attempt`),
  UNIQUE KEY `exam_submissions_session_id_key` (`session_id`),
  KEY `exam_submissions_user_id_exam_id_idx` (`user_id`,`exam_id`),
  KEY `exam_submissions_exam_id_fkey` (`exam_id`),
  CONSTRAINT `exam_submissions_exam_id_fkey` FOREIGN KEY (`exam_id`) REFERENCES `exams` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `exam_submissions_session_id_fkey` FOREIGN KEY (`session_id`) REFERENCES `exam_sessions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `exam_submissions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exam_token_redemptions` (
  `id` varchar(191) NOT NULL,
  `token_id` varchar(191) NOT NULL,
  `user_id` varchar(191) NOT NULL,
  `redeemed_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `exam_token_redemptions_token_id_user_id_key` (`token_id`,`user_id`),
  KEY `exam_token_redemptions_user_id_fkey` (`user_id`),
  CONSTRAINT `exam_token_redemptions_token_id_fkey` FOREIGN KEY (`token_id`) REFERENCES `exam_access_tokens` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `exam_token_redemptions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `exams` (
  `id` varchar(191) NOT NULL,
  `exam_code` varchar(191) NOT NULL,
  `name` varchar(191) NOT NULL,
  `duration_minutes` int(11) NOT NULL,
  `passing_grade` int(11) NOT NULL,
  `general_instructions` text DEFAULT NULL,
  `start_time` datetime(3) DEFAULT NULL,
  `end_time` datetime(3) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `media_base_url` varchar(191) DEFAULT NULL,
  `exam_mode` enum('strict','try_out') NOT NULL DEFAULT 'strict',
  `shuffle_questions` tinyint(1) NOT NULL DEFAULT 0,
  `shuffle_options` tinyint(1) NOT NULL DEFAULT 0,
  `language` varchar(191) NOT NULL DEFAULT 'English',
  `subject` varchar(191) DEFAULT NULL,
  `type_distribution` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`type_distribution`)),
  `difficulty_distribution` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`difficulty_distribution`)),
  `media_targets` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`media_targets`)),
  `created_by` varchar(191) DEFAULT NULL,
  `created_by_name` varchar(191) DEFAULT NULL,
  `seb_required` tinyint(1) NOT NULL DEFAULT 0,
  `seb_secret` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `exams_exam_code_key` (`exam_code`),
  KEY `exams_created_by_idx` (`created_by`),
  KEY `exams_active_idx` (`active`),
  CONSTRAINT `exams_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `learning_objectives` (
  `id` varchar(191) NOT NULL,
  `language` varchar(191) NOT NULL,
  `subject` varchar(191) NOT NULL,
  `topic` varchar(191) NOT NULL,
  `subtopic` varchar(191) DEFAULT NULL,
  `text` text NOT NULL,
  `created_by` varchar(191) DEFAULT NULL,
  `created_by_name` varchar(191) DEFAULT NULL,
  `uploaded_by` varchar(191) DEFAULT NULL,
  `uploaded_by_name` varchar(191) DEFAULT NULL,
  `source_file_name` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `curriculum` enum('kurikulum_merdeka','as_a_level','ib','olympiad') NOT NULL DEFAULT 'kurikulum_merdeka',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `learning_objectives_subject_idx` (`subject`),
  KEY `learning_objectives_uploaded_by_idx` (`uploaded_by`),
  KEY `learning_objectives_subject_topic_idx` (`subject`,`topic`),
  KEY `learning_objectives_created_by_fkey` (`created_by`),
  KEY `learning_objectives_curriculum_subject_idx` (`curriculum`,`subject`),
  KEY `learning_objectives_curriculum_subject_sort_order_idx` (`curriculum`,`subject`,`sort_order`),
  CONSTRAINT `learning_objectives_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `learning_objectives_uploaded_by_fkey` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `student_classes` (
  `id` varchar(191) NOT NULL,
  `name` varchar(191) NOT NULL,
  `source_file_name` varchar(191) DEFAULT NULL,
  `created_by` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `academic_year` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_classes_created_by_name_academic_year_key` (`created_by`,`name`,`academic_year`),
  KEY `student_classes_name_academic_year_idx` (`name`,`academic_year`),
  CONSTRAINT `student_classes_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_credentials` (
  `user_id` varchar(191) NOT NULL,
  `password_hash` varchar(191) NOT NULL,
  `password_set_by` varchar(191) DEFAULT NULL,
  `password_set_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `last_sign_in_at` datetime(3) DEFAULT NULL,
  `failed_attempts` int(11) NOT NULL DEFAULT 0,
  `locked_until` datetime(3) DEFAULT NULL,
  `password_plain` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `user_credentials_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `users` (
  `id` varchar(191) NOT NULL,
  `username` varchar(191) NOT NULL,
  `full_name` varchar(191) NOT NULL,
  `role` enum('student','teacher','admin') NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `subject` varchar(191) DEFAULT NULL,
  `capabilities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`capabilities`)),
  `created_by` varchar(191) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `updated_at` datetime(3) NOT NULL,
  `token_version` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_key` (`username`),
  KEY `users_role_idx` (`role`),
  KEY `users_created_by_fkey` (`created_by`),
  CONSTRAINT `users_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
